name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Skip CI check
        uses: mstachniuk/ci-skip@v1

      - name: Set up Node.js
        if: env.CI_SKIP == 'false'
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set yarn cache directory
        if: env.CI_SKIP == 'false'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Get yarn cache
        uses: actions/cache@v3
        if: env.CI_SKIP == 'false'
        id: yarn-cache
        with:
          path: ${{steps.yarn-cache-dir-path.outputs.dir}}
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: ${{runner.os}}-yarn-

      - name: Build, lint and test
        if: env.CI_SKIP == 'false'
        run: |
          yarn
          yarn lint
          yarn dist
